# Nom du workflow GitHub Actions
name: CI project

# Déclencher le workflow lors d'un push et du pull_request
on:
  push:
  pull_request:

jobs:
  # Nom du job
  build-and-test:
    # Utiliser une image Ubuntu pour l'exécution du job
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # Matrice pour exécuter le job sur deux architectures différentes
        platform: [linux/amd64, linux/arm64/v8]

    steps:
    - name: Checkout Code
      # Utiliser l'action pour récupérer le code source du dépôt
      uses: actions/checkout@v2

    # Mise en place conditionnelle de QEMU pour les architectures ARM64
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      # Cette étape est nécessaire pour émuler l'architecture ARM64 sur x86_64

    - name: Build and run Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: ${{ matrix.platform }}
        load: true
        push: false
        tags: user/app:latest
      # Construction de l'image Docker pour les différentes architectures

    - name: Run tests
      run: docker run user/app:latest
      # Exécution des tests sur l'image Docker générée
